project_name: tbd-release

builds:
- skip: true

dist: releaser

snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}"

git:
  tag_sort: -version:creatordate

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  prerelease: auto
  header: |
    ## Upgrading

    This project uses the semver versioning and ensures that following rules:

    The patch release does not introduce any breaking changes. So if you are upgrading from v1.5.1 to v1.5.3 there should be no special instructions to follow.
    The minor release might introduce minor changes with a workaround. If you are upgrading from v1.3.0 to v1.5.2 please make sure to check upgrading details in both v1.3 to v1.4 and v1.4 to v1.5 upgrading instructions.
    The major release introduces backward incompatible behavior changes. It is recommended to take a backup using disaster recovery guide.
  footer: |
    **Full Changelog**: https://github.com/ixxeL-actions/tbd-release/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!

    Want to be one of them?
   





# changelog:
#   use:
#     github
#   sort: asc
#   abbrev: 0
#   groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
#     - title: 'Features'
#       regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
#       order: 100
#     - title: 'Bug fixes'
#       regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
#       order: 200
#     - title: 'Documentation'
#       regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
#       order: 300
#     - title: 'Dependency updates'
#       regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
#       order: 400
#     - title: 'Other work'
#       order: 999
#   filters:
#     exclude:
#       - '^test:'
#       - '^.*?Bump(\([[:word:]]+\))?.+$'
#       - '^.*?[Bot](\([[:word:]]+\))?.+$'
